
POST https://ineedadeveloper.com/api/v1/listing/add-jobs
Content-Type: application/json

{
  "user_id":26,
  "title": "title",
  "project_level": "medium",
  "project_duration": "weekly",
  "english_level": "fluent",
  "project_cost": 500,
  "description": "Project description"
}

### Get request with a header
GET https://ineedadeveloper.com/api/v1/listing/add-jobs
Accept: application/json
###

POST https://www.ineedadeveloper.com/register
Content-Type: application/json

{
first_name: cccc,
last_name: ddddddd,
email: amgunity@gmail.com,
locations: 237,
password: djwth10,
password_confirmation: djwth10,
role: employer,
employees: 10,
department: 4,
department_name:"d_name",
termsconditions: on,
}

###